import type { PackagingModelId, MaterialType } from '../types/packaging';

export interface MockupCardItem {
  id: string;
  modelId: PackagingModelId;
  title: string;
  category: string;
  categorySlug: 'boxes' | 'bottles' | 'food' | 'pouches' | 'cans' | 'jars' | 'tubes' | 'cups' | 'apparel';
  dimensionsText: string;
  dims: { width: number; height: number; depth: number };
  defaultMaterial: MaterialType;
  colorSwatches: string[];
  is3D: boolean;
  modelCode: string;
  thumbnailSvg: string;
}

export const MOCKUP_CATALOG: MockupCardItem[] = [
  // --- Pouches & Sachets & Bags (Shown in Screenshot 177) ---
  {
    id: 'pouch-01',
    modelId: 'standup_pouch',
    title: 'Standing pouch mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '75 × 130 × 225 mm',
    dims: { width: 130, height: 225, depth: 75 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#ffffff', '#cbd5e1', '#d4af37', '#a855f7'],
    is3D: true,
    modelCode: '604050',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-02',
    modelId: 'standup_pouch',
    title: '10 × 7 × 22 stand-up coffee pouch mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '100 × 70 × 220 mm',
    dims: { width: 100, height: 220, depth: 70 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#a7f3d0', '#ffffff', '#78350f', '#d4af37'],
    is3D: true,
    modelCode: '604051',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-03',
    modelId: 'standup_pouch',
    title: 'Zipper pouch mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '120 × 60 × 180 mm',
    dims: { width: 120, height: 180, depth: 60 },
    defaultMaterial: 'metallic_foil',
    colorSwatches: ['#f472b6', '#ffffff', '#38bdf8'],
    is3D: true,
    modelCode: '604052',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-04',
    modelId: 'standup_pouch',
    title: '10 × 8 × 26 stand-up snack pouch mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '100 × 80 × 260 mm',
    dims: { width: 100, height: 260, depth: 80 },
    defaultMaterial: 'coated_gloss',
    colorSwatches: ['#93c5fd', '#ffffff', '#cbd5e1', '#d97706'],
    is3D: true,
    modelCode: '604053',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-05',
    modelId: 'standup_pouch',
    title: '13 × 9 × 24 stand-up tea pouch mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '130 × 90 × 240 mm',
    dims: { width: 130, height: 240, depth: 90 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#6ee7b7', '#ffffff', '#1e293b'],
    is3D: true,
    modelCode: '604054',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-06',
    modelId: 'standup_pouch',
    title: 'Classic coffee pouch Mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '110 × 75 × 230 mm',
    dims: { width: 110, height: 230, depth: 75 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#fef08a', '#ffffff', '#334155', '#d4af37'],
    is3D: true,
    modelCode: '604055',
    thumbnailSvg: '👝',
  },
  {
    id: 'pouch-07',
    modelId: 'standup_pouch',
    title: 'Paper coffee bag packaging mockup',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '120 × 80 × 250 mm',
    dims: { width: 120, height: 250, depth: 80 },
    defaultMaterial: 'kraft_paper',
    colorSwatches: ['#c49a6c', '#ffffff', '#78350f'],
    is3D: true,
    modelCode: '604056',
    thumbnailSvg: '🛍️',
  },
  {
    id: 'pouch-08',
    modelId: 'shopping_bag',
    title: 'Coffee bag mockup with tin tie',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '100 × 65 × 240 mm',
    dims: { width: 100, height: 240, depth: 65 },
    defaultMaterial: 'kraft_paper',
    colorSwatches: ['#ffffff', '#c49a6c', '#1e293b'],
    is3D: true,
    modelCode: '604057',
    thumbnailSvg: '🛍️',
  },

  // --- Boxes ---
  {
    id: 'box-01',
    modelId: 'mailer_box',
    title: 'E-commerce mailer box mockup',
    category: 'Boxes',
    categorySlug: 'boxes',
    dimensionsText: '200 × 60 × 150 mm',
    dims: { width: 200, height: 60, depth: 150 },
    defaultMaterial: 'kraft_paper',
    colorSwatches: ['#c49a6c', '#ffffff', '#1e293b', '#ea580c'],
    is3D: true,
    modelCode: '601001',
    thumbnailSvg: '📦',
  },
  {
    id: 'box-02',
    modelId: 'tuck_box',
    title: 'Straight tuck end carton box mockup',
    category: 'Boxes',
    categorySlug: 'boxes',
    dimensionsText: '75 × 130 × 75 mm',
    dims: { width: 75, height: 130, depth: 75 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#ffffff', '#1e293b', '#6366f1', '#d4af37'],
    is3D: true,
    modelCode: '601002',
    thumbnailSvg: '🎁',
  },
  {
    id: 'box-03',
    modelId: 'mailer_box',
    title: 'Corrugated subscription shipping box',
    category: 'Boxes',
    categorySlug: 'boxes',
    dimensionsText: '250 × 80 × 180 mm',
    dims: { width: 250, height: 80, depth: 180 },
    defaultMaterial: 'kraft_paper',
    colorSwatches: ['#c49a6c', '#ffffff', '#0f172a'],
    is3D: true,
    modelCode: '601003',
    thumbnailSvg: '📦',
  },
  {
    id: 'box-04',
    modelId: 'tuck_box',
    title: 'Cosmetic skincare perfume retail box',
    category: 'Boxes',
    categorySlug: 'boxes',
    dimensionsText: '60 × 140 × 60 mm',
    dims: { width: 60, height: 140, depth: 60 },
    defaultMaterial: 'coated_gloss',
    colorSwatches: ['#ffffff', '#f472b6', '#d4af37', '#1e293b'],
    is3D: true,
    modelCode: '601004',
    thumbnailSvg: '🎁',
  },

  // --- Bottles ---
  {
    id: 'bottle-01',
    modelId: 'dropper_bottle',
    title: 'Amber glass dropper serum bottle mockup',
    category: 'Bottles',
    categorySlug: 'bottles',
    dimensionsText: '42 × 115 × 42 mm',
    dims: { width: 42, height: 115, depth: 42 },
    defaultMaterial: 'glass_amber',
    colorSwatches: ['#78350f', '#ffffff', '#d4af37', '#111827'],
    is3D: true,
    modelCode: '602001',
    thumbnailSvg: '🧴',
  },
  {
    id: 'bottle-02',
    modelId: 'dropper_bottle',
    title: 'Clear glass dropper bottle 30ml',
    category: 'Bottles',
    categorySlug: 'bottles',
    dimensionsText: '38 × 105 × 38 mm',
    dims: { width: 38, height: 105, depth: 38 },
    defaultMaterial: 'glass_clear',
    colorSwatches: ['#93c5fd', '#ffffff', '#000000'],
    is3D: true,
    modelCode: '602002',
    thumbnailSvg: '🧴',
  },

  // --- Cans ---
  {
    id: 'can-01',
    modelId: 'beverage_can',
    title: 'Sleek aluminum soda beverage can 330ml',
    category: 'Cans',
    categorySlug: 'cans',
    dimensionsText: '66 × 145 × 66 mm',
    dims: { width: 66, height: 145, depth: 66 },
    defaultMaterial: 'metallic_foil',
    colorSwatches: ['#cbd5e1', '#00f2fe', '#f43f5e', '#111827'],
    is3D: true,
    modelCode: '603001',
    thumbnailSvg: '🥫',
  },
  {
    id: 'can-02',
    modelId: 'beverage_can',
    title: 'Craft beer tallboy aluminum can 500ml',
    category: 'Cans',
    categorySlug: 'cans',
    dimensionsText: '66 × 168 × 66 mm',
    dims: { width: 66, height: 168, depth: 66 },
    defaultMaterial: 'metallic_foil',
    colorSwatches: ['#cbd5e1', '#d97706', '#1e293b'],
    is3D: true,
    modelCode: '603002',
    thumbnailSvg: '🥫',
  },

  // --- Tubes & Jars & Cups ---
  {
    id: 'cup-01',
    modelId: 'paper_cup',
    title: 'Takeaway paper coffee cup with lid 12oz',
    category: 'Containers & Cups & Bowls',
    categorySlug: 'cups',
    dimensionsText: '90 × 135 × 90 mm',
    dims: { width: 90, height: 135, depth: 90 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#ffffff', '#c49a6c', '#1e293b', '#22c55e'],
    is3D: true,
    modelCode: '605001',
    thumbnailSvg: '☕',
  },
  {
    id: 'tube-01',
    modelId: 'cosmetic_tube',
    title: 'Cosmetic cream squeeze tube mockup 100ml',
    category: 'Tubes',
    categorySlug: 'tubes',
    dimensionsText: '50 × 160 × 32 mm',
    dims: { width: 50, height: 160, depth: 32 },
    defaultMaterial: 'coated_matte',
    colorSwatches: ['#ffffff', '#c084fc', '#fbcfe8', '#1e293b'],
    is3D: true,
    modelCode: '606001',
    thumbnailSvg: '🧴',
  },
  {
    id: 'jar-01',
    modelId: 'cosmetic_jar',
    title: 'Cosmetic cream facial jar with screw cap',
    category: 'Jars',
    categorySlug: 'jars',
    dimensionsText: '72 × 55 × 72 mm',
    dims: { width: 72, height: 55, depth: 72 },
    defaultMaterial: 'plastic_frosted',
    colorSwatches: ['#ffffff', '#cbd5e1', '#d4af37', '#111827'],
    is3D: true,
    modelCode: '607001',
    thumbnailSvg: '🏺',
  },
  {
    id: 'bag-01',
    modelId: 'shopping_bag',
    title: 'Kraft paper retail shopping bag with cord',
    category: 'Pouches & Sachets & Bags',
    categorySlug: 'pouches',
    dimensionsText: '220 × 280 × 100 mm',
    dims: { width: 220, height: 280, depth: 100 },
    defaultMaterial: 'kraft_paper',
    colorSwatches: ['#c49a6c', '#ffffff', '#0f172a', '#e11d48'],
    is3D: true,
    modelCode: '608001',
    thumbnailSvg: '🛍️',
  },
];
