import type { PackagingModelDef, PackagingModelId } from '../types/packaging';

export const PACKAGING_MODELS: Record<PackagingModelId, PackagingModelDef> = {
  mailer_box: {
    id: 'mailer_box',
    name: 'Kotak Mailer (E-Commerce)',
    nameEn: 'Mailer Box (E-Commerce)',
    category: 'boxes',
    categoryName: 'Kotak & Kardus',
    description: 'Kotak kardus berengsel dengan lid lipat pengunci depan, standar kemasan e-commerce premium & unboxing.',
    thumbnail: '📦',
    defaultDimensions: { width: 200, height: 60, depth: 150 },
    minDimensions: { width: 100, height: 30, depth: 80 },
    maxDimensions: { width: 350, height: 120, depth: 250 },
    availableFaces: [
      { id: 'full_dieline', name: 'Jaring-jaring Lengkap', nameEn: 'Full Dieline' },
      { id: 'lid', name: 'Tutup Atas Luar', nameEn: 'Top Outer Lid' },
      { id: 'front', name: 'Sisi Depan', nameEn: 'Front Face' },
      { id: 'back', name: 'Sisi Belakang', nameEn: 'Back Face' },
      { id: 'left', name: 'Samping Kiri', nameEn: 'Left Flap' },
      { id: 'right', name: 'Samping Kanan', nameEn: 'Right Flap' },
      { id: 'bottom', name: 'Dasar Kotak (Dalam)', nameEn: 'Inside Bottom' },
    ],
    textureWidth: 2048,
    textureHeight: 2048,
    hasOpenAnimation: true,
    openLabel: 'Buka / Tutup Lid',
    defaultMaterial: 'kraft_paper',
    allowedMaterials: ['kraft_paper', 'kraft_white', 'coated_matte', 'coated_gloss', 'metallic_foil'],
  },
  tuck_box: {
    id: 'tuck_box',
    name: 'Kotak Lipat Standar (Tuck Box)',
    nameEn: 'Standard Tuck Box',
    category: 'boxes',
    categoryName: 'Kotak & Kardus',
    description: 'Kotak karton lipat serbaguna untuk kosmetik, suplemen kesehatan, obat, parfum, dan retail packaging.',
    thumbnail: '🎁',
    defaultDimensions: { width: 75, height: 130, depth: 75 },
    minDimensions: { width: 40, height: 60, depth: 40 },
    maxDimensions: { width: 160, height: 260, depth: 160 },
    availableFaces: [
      { id: 'full_dieline', name: 'Jaring-jaring Lengkap', nameEn: 'Full Dieline' },
      { id: 'front', name: 'Sisi Depan (Utama)', nameEn: 'Front Face' },
      { id: 'back', name: 'Sisi Belakang', nameEn: 'Back Face' },
      { id: 'left', name: 'Samping Kiri', nameEn: 'Left Side' },
      { id: 'right', name: 'Samping Kanan', nameEn: 'Right Side' },
      { id: 'top', name: 'Flap Atas (Tutup)', nameEn: 'Top Tuck Flap' },
      { id: 'bottom', name: 'Dasar Bawah', nameEn: 'Bottom Flap' },
    ],
    textureWidth: 2048,
    textureHeight: 2048,
    hasOpenAnimation: true,
    openLabel: 'Buka Flap Atas',
    defaultMaterial: 'coated_matte',
    allowedMaterials: ['coated_matte', 'coated_gloss', 'kraft_paper', 'kraft_white', 'metallic_foil'],
  },
  beverage_can: {
    id: 'beverage_can',
    name: 'Kaleng Minuman Aluminium',
    nameEn: 'Beverage Aluminum Can',
    category: 'bottles',
    categoryName: 'Botol & Kaleng',
    description: 'Kaleng aluminium 330ml/500ml untuk soda, bir kerajinan, cold brew coffee, dan minuman berenergi.',
    thumbnail: '🥫',
    defaultDimensions: { width: 66, height: 150, depth: 66, radius: 33 },
    minDimensions: { width: 50, height: 100, depth: 50, radius: 25 },
    maxDimensions: { width: 80, height: 200, depth: 80, radius: 40 },
    availableFaces: [
      { id: 'full_dieline', name: 'Label Melingkar 360°', nameEn: '360° Wrap Label' },
      { id: 'front', name: 'Depan Tengah', nameEn: 'Front Center' },
      { id: 'back', name: 'Belakang (Nutrisi/Barcode)', nameEn: 'Back Facts' },
    ],
    textureWidth: 2048,
    textureHeight: 1200,
    hasOpenAnimation: false,
    defaultMaterial: 'metallic_foil',
    allowedMaterials: ['metallic_foil', 'coated_gloss', 'coated_matte'],
  },
  dropper_bottle: {
    id: 'dropper_bottle',
    name: 'Botol Pipet Serum (Dropper)',
    nameEn: 'Dropper Serum Bottle',
    category: 'bottles',
    categoryName: 'Botol & Kaleng',
    description: 'Botol kaca premium dengan pipet tetes karet untuk serum kecantikan, minyak esensial, & aromaterapi.',
    thumbnail: '🧴',
    defaultDimensions: { width: 42, height: 115, depth: 42, radius: 21 },
    minDimensions: { width: 30, height: 80, depth: 30, radius: 15 },
    maxDimensions: { width: 65, height: 160, depth: 65, radius: 32 },
    availableFaces: [
      { id: 'full_dieline', name: 'Label Badan Botol', nameEn: 'Body Wrap Label' },
      { id: 'front', name: 'Label Depan', nameEn: 'Front Face' },
      { id: 'back', name: 'Label Belakang', nameEn: 'Back Face' },
    ],
    textureWidth: 2048,
    textureHeight: 1024,
    hasOpenAnimation: true,
    openLabel: 'Buka Pipet',
    defaultMaterial: 'glass_amber',
    allowedMaterials: ['glass_amber', 'glass_clear', 'plastic_frosted', 'coated_matte'],
  },
  standup_pouch: {
    id: 'standup_pouch',
    name: 'Kemasan Stand-up Pouch (Doypack)',
    nameEn: 'Stand-up Pouch (Doypack)',
    category: 'pouches',
    categoryName: 'Pouch & Tas',
    description: 'Pouch bersegel dengan ziplock dan bottom gusset untuk biji kopi, teh, keripik, granola, dan bubuk makanan.',
    thumbnail: '👝',
    defaultDimensions: { width: 140, height: 210, depth: 70 },
    minDimensions: { width: 100, height: 150, depth: 40 },
    maxDimensions: { width: 220, height: 320, depth: 100 },
    availableFaces: [
      { id: 'full_dieline', name: 'Depan & Belakang Pouch', nameEn: 'Front & Back Net' },
      { id: 'front', name: 'Sisi Depan', nameEn: 'Front Face' },
      { id: 'back', name: 'Sisi Belakang', nameEn: 'Back Face' },
    ],
    textureWidth: 2048,
    textureHeight: 1400,
    hasOpenAnimation: false,
    defaultMaterial: 'coated_matte',
    allowedMaterials: ['coated_matte', 'kraft_paper', 'metallic_foil', 'coated_gloss'],
  },
  paper_cup: {
    id: 'paper_cup',
    name: 'Gelas Kopi Kertas (Coffee Cup)',
    nameEn: 'Paper Coffee Cup',
    category: 'cups_tubes',
    categoryName: 'Gelas & Tube',
    description: 'Gelas takeaway kopi 12oz dengan tutup lid plastik snap-on dan pelindung panas karton (sleeve).',
    thumbnail: '☕',
    defaultDimensions: { width: 90, height: 135, depth: 90, radius: 45 },
    minDimensions: { width: 70, height: 95, depth: 70, radius: 35 },
    maxDimensions: { width: 105, height: 165, depth: 105, radius: 52 },
    availableFaces: [
      { id: 'full_dieline', name: 'Wrap Melingkar Gelas', nameEn: 'Full Cup Wrap' },
      { id: 'front', name: 'Tampak Depan Logo', nameEn: 'Front Logo' },
      { id: 'back', name: 'Tampak Belakang', nameEn: 'Back Side' },
    ],
    textureWidth: 2048,
    textureHeight: 1024,
    hasOpenAnimation: true,
    openLabel: 'Buka Tutup Cup',
    defaultMaterial: 'coated_matte',
    allowedMaterials: ['coated_matte', 'kraft_paper', 'coated_gloss'],
  },
  shopping_bag: {
    id: 'shopping_bag',
    name: 'Tas Belanja Kertas (Paper Bag)',
    nameEn: 'Paper Shopping Bag',
    category: 'pouches',
    categoryName: 'Pouch & Tas',
    description: 'Paper bag mewah dengan lipatan samping accordion dan tali pegangan jinjing (twisted rope handle).',
    thumbnail: '🛍️',
    defaultDimensions: { width: 220, height: 280, depth: 100 },
    minDimensions: { width: 150, height: 180, depth: 70 },
    maxDimensions: { width: 340, height: 420, depth: 150 },
    availableFaces: [
      { id: 'full_dieline', name: 'Jaring-jaring Bag', nameEn: 'Bag Net' },
      { id: 'front', name: 'Sisi Depan', nameEn: 'Front Panel' },
      { id: 'back', name: 'Sisi Belakang', nameEn: 'Back Panel' },
      { id: 'left', name: 'Lipatan Samping Kiri', nameEn: 'Left Gusset' },
      { id: 'right', name: 'Lipatan Samping Kanan', nameEn: 'Right Gusset' },
    ],
    textureWidth: 2048,
    textureHeight: 1800,
    hasOpenAnimation: false,
    defaultMaterial: 'kraft_paper',
    allowedMaterials: ['kraft_paper', 'kraft_white', 'coated_matte', 'coated_gloss'],
  },
  cosmetic_tube: {
    id: 'cosmetic_tube',
    name: 'Tube Kosmetik & Salep',
    nameEn: 'Cosmetic Squeeze Tube',
    category: 'cups_tubes',
    categoryName: 'Gelas & Tube',
    description: 'Tube fleksibel dengan ujung segel crimped datar dan tutup screw cap untuk sabun cuci muka, lotion, & scrub.',
    thumbnail: '🧴',
    defaultDimensions: { width: 50, height: 160, depth: 32 },
    minDimensions: { width: 35, height: 100, depth: 25 },
    maxDimensions: { width: 65, height: 200, depth: 40 },
    availableFaces: [
      { id: 'full_dieline', name: 'Label Depan & Belakang', nameEn: 'Front & Back Label' },
      { id: 'front', name: 'Depan (Merk & Khasiat)', nameEn: 'Front Brand' },
      { id: 'back', name: 'Belakang (Komposisi/Cara Pakai)', nameEn: 'Back Directions' },
    ],
    textureWidth: 2048,
    textureHeight: 1400,
    hasOpenAnimation: true,
    openLabel: 'Lepas Tutup Tube',
    defaultMaterial: 'coated_matte',
    allowedMaterials: ['coated_matte', 'coated_gloss', 'plastic_frosted', 'metallic_foil'],
  },
  cosmetic_jar: {
    id: 'cosmetic_jar',
    name: 'Jar Krim Kosmetik / Masker',
    nameEn: 'Cosmetic Cream Jar',
    category: 'bottles',
    categoryName: 'Botol & Kaleng',
    description: 'Jar bundar kaca/plastik dengan tutup ulir metalik untuk krim pelembab malam, masker, & pomade.',
    thumbnail: '🏺',
    defaultDimensions: { width: 72, height: 55, depth: 72, radius: 36 },
    minDimensions: { width: 45, height: 35, depth: 45, radius: 22 },
    maxDimensions: { width: 100, height: 80, depth: 100, radius: 50 },
    availableFaces: [
      { id: 'full_dieline', name: 'Label Tutup & Samping', nameEn: 'Lid & Side Label' },
      { id: 'top', name: 'Tutup Atas (Top Lid)', nameEn: 'Top Lid Sticker' },
      { id: 'front', name: 'Samping Depan', nameEn: 'Side Front' },
    ],
    textureWidth: 2048,
    textureHeight: 1024,
    hasOpenAnimation: true,
    openLabel: 'Buka Tutup Jar',
    defaultMaterial: 'plastic_frosted',
    allowedMaterials: ['plastic_frosted', 'glass_clear', 'glass_amber', 'coated_matte', 'metallic_foil'],
  },
};
