import type { BrandPreset } from '../types/packaging';

export const BRAND_PRESETS: BrandPreset[] = [
  {
    id: 'kopi_nusantara',
    title: 'Kopi Nusantara Roasters',
    modelId: 'tuck_box',
    category: 'Coffee & Food',
    material: 'kraft_paper',
    backgroundColor: '#3b2413',
    accentColor: '#d4af37',
    lighting: 'warm_commercial',
    description: 'Kemasan artisan biji kopi spesialti dengan nuansa kraft premium & aksen emas klasik.',
    layers: [
      {
        id: 'bg_stripe',
        name: 'Garis Pita Emas',
        type: 'shape',
        shapeType: 'rect',
        x: 520,
        y: 600,
        width: 460,
        height: 12,
        fill: '#d4af37',
        strokeColor: 'transparent',
        strokeWidth: 0,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'brand_title',
        name: 'Nama Merk',
        type: 'text',
        text: 'KOPI NUSANTARA',
        fontFamily: 'Montserrat',
        fontSize: 34,
        fontWeight: '800',
        color: '#fef3c7',
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        x: 750,
        y: 720,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'sub_title',
        name: 'Kategori Biji',
        type: 'text',
        text: 'SINGLE ORIGIN GAYO HIGHLANDS',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '600',
        color: '#d4af37',
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1.2,
        x: 750,
        y: 770,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'flavor_notes',
        name: 'Tasting Notes',
        type: 'text',
        text: 'Notes: Brown Sugar • Jasmine • Tangerine\nElevation: 1,600 MASL • Process: Full Washed',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: '400',
        color: '#e2e8f0',
        textAlign: 'center',
        letterSpacing: 1,
        lineHeight: 1.5,
        x: 750,
        y: 860,
        rotation: 0,
        opacity: 0.9,
      },
      {
        id: 'badge_organic',
        name: 'Stempel Organik',
        type: 'badge',
        badgeType: 'organic',
        size: 90,
        color: '#d4af37',
        x: 650,
        y: 1040,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'badge_halal',
        name: 'Stempel Halal',
        type: 'badge',
        badgeType: 'halal',
        size: 90,
        color: '#d4af37',
        x: 850,
        y: 1040,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'netto',
        name: 'Berat Bersih',
        type: 'text',
        text: 'NET WT. 250G / 8.8 OZ',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '700',
        color: '#fef3c7',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        x: 750,
        y: 1160,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'back_story',
        name: 'Cerita Belakang',
        type: 'text',
        text: 'Biji kopi pilihan yang dipetik dari lereng pegunungan dataran tinggi Gayo, Aceh. Dipanggang secara presisi profil medium-roast untuk mengeluarkan aroma bunga dan manis karamel alami.',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: '400',
        color: '#cbd5e1',
        textAlign: 'center',
        letterSpacing: 0.5,
        lineHeight: 1.6,
        x: 1670,
        y: 740,
        rotation: 0,
        opacity: 0.95,
      },
      {
        id: 'barcode_back',
        name: 'Barcode Produk',
        type: 'barcode',
        code: '899723450912',
        width: 240,
        height: 100,
        color: '#1e293b',
        bgColor: '#ffffff',
        showText: true,
        x: 1550,
        y: 1100,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'top_logo',
        name: 'Logo Tutup Atas',
        type: 'text',
        text: 'KN',
        fontFamily: 'Playfair Display',
        fontSize: 52,
        fontWeight: '700',
        color: '#d4af37',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        x: 750,
        y: 350,
        rotation: 0,
        opacity: 1,
      },
    ],
  },
  {
    id: 'luxe_serum',
    title: 'Luxe Botanicals Serum',
    modelId: 'dropper_bottle',
    category: 'Cosmetics & Skincare',
    material: 'glass_amber',
    backgroundColor: '#1c1917',
    accentColor: '#fbbf24',
    lighting: 'dramatic_rim',
    description: 'Botol pipet serum mewah bernuansa minimalis ala apothecary Prancis & Korea.',
    layers: [
      {
        id: 'brand_name',
        name: 'Brand Header',
        type: 'text',
        text: 'L U X E  B O T A N I C A L S',
        fontFamily: 'Inter',
        fontSize: 26,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1.2,
        x: 1024,
        y: 340,
        rotation: 0,
        opacity: 0.95,
      },
      {
        id: 'serum_title',
        name: 'Nama Produk',
        type: 'text',
        text: 'BAKUCHIOL & NIACINAMIDE 10%',
        fontFamily: 'Space Grotesk',
        fontSize: 32,
        fontWeight: '700',
        color: '#fef08a',
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1.2,
        x: 1024,
        y: 430,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'serum_desc',
        name: 'Deskripsi Manfaat',
        type: 'text',
        text: 'ADVANCED CELLULAR RENEWAL OIL\nTargeting Fine Lines, Elasticity & Radiant Glow',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '400',
        color: '#e2e8f0',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.6,
        x: 1024,
        y: 520,
        rotation: 0,
        opacity: 0.85,
      },
      {
        id: 'volume_text',
        name: 'Volume Netto',
        type: 'text',
        text: '30 ml • 1.01 fl. oz. e',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        x: 1024,
        y: 650,
        rotation: 0,
        opacity: 0.9,
      },
      {
        id: 'qr_verify',
        name: 'QR Keaslian',
        type: 'qrcode',
        content: 'https://luxebotanicals.com/verify?batch=LX-2026',
        size: 110,
        color: '#ffffff',
        bgColor: '#000000',
        x: 1650,
        y: 420,
        rotation: 0,
        opacity: 0.9,
      },
    ],
  },
  {
    id: 'neon_volt',
    title: 'Volt Surge Energy Can',
    modelId: 'beverage_can',
    category: 'Beverages',
    material: 'metallic_foil',
    backgroundColor: '#090d16',
    accentColor: '#00f2fe',
    lighting: 'neon_cyber',
    description: 'Kaleng minuman energi futuristik dengan aksen metalik neon berkilau.',
    layers: [
      {
        id: 'can_brand',
        name: 'Volt Logo',
        type: 'text',
        text: 'VOLT',
        fontFamily: 'Bebas Neue',
        fontSize: 130,
        fontWeight: '800',
        color: '#00f2fe',
        textAlign: 'center',
        letterSpacing: 6,
        lineHeight: 1,
        x: 1024,
        y: 400,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'can_sub',
        name: 'Sub-brand',
        type: 'text',
        text: 'SURGE // ZERO SUGAR',
        fontFamily: 'Space Grotesk',
        fontSize: 26,
        fontWeight: '700',
        color: '#4facfe',
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        x: 1024,
        y: 500,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'can_flavor',
        name: 'Varian Rasa',
        type: 'text',
        text: 'ELECTRIC CITRUS & TAURINE',
        fontFamily: 'Inter',
        fontSize: 20,
        fontWeight: '600',
        color: '#ffffff',
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1,
        x: 1024,
        y: 580,
        rotation: 0,
        opacity: 0.9,
      },
      {
        id: 'can_vol',
        name: 'Isi Kaleng',
        type: 'text',
        text: '330 mL (11.1 FL OZ)',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: '700',
        color: '#94a3b8',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        x: 1024,
        y: 750,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'barcode_can',
        name: 'Barcode Samping',
        type: 'barcode',
        code: '079357318892',
        width: 180,
        height: 80,
        color: '#000000',
        bgColor: '#ffffff',
        showText: true,
        x: 1680,
        y: 450,
        rotation: 90,
        opacity: 0.9,
      },
    ],
  },
  {
    id: 'urban_mailer',
    title: 'Urban Kicks Mailer Box',
    modelId: 'mailer_box',
    category: 'E-Commerce & Retail',
    material: 'kraft_paper',
    backgroundColor: '#c49a6c',
    accentColor: '#ea580c',
    lighting: 'pure_catalog',
    description: 'Kotak kardus shipping berengsel dengan tape streetwear & petunjuk pengiriman.',
    layers: [
      {
        id: 'lid_brand',
        name: 'Merk Tutup Atas',
        type: 'text',
        text: 'URBAN KICKS CO.',
        fontFamily: 'Bebas Neue',
        fontSize: 90,
        fontWeight: '800',
        color: '#1e293b',
        textAlign: 'center',
        letterSpacing: 8,
        lineHeight: 1,
        x: 1024,
        y: 480,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'lid_tagline',
        name: 'Tagline',
        type: 'text',
        text: 'ENGINEERED FOR THE CONCRETE JUNGLE',
        fontFamily: 'Space Grotesk',
        fontSize: 22,
        fontWeight: '600',
        color: '#ea580c',
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1,
        x: 1024,
        y: 560,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'inner_welcome',
        name: 'Pesan Unboxing Dalam',
        type: 'text',
        text: 'WELCOME TO THE MOVEMENT.\nTAG YOUR FIT #URBANKICKS',
        fontFamily: 'Space Grotesk',
        fontSize: 32,
        fontWeight: '700',
        color: '#0f172a',
        textAlign: 'center',
        letterSpacing: 3,
        lineHeight: 1.4,
        x: 1024,
        y: 1120,
        rotation: 0,
        opacity: 0.9,
      },
      {
        id: 'recycle_stamp',
        name: 'Stempel Daur Ulang',
        type: 'badge',
        badgeType: 'recyclable',
        size: 100,
        color: '#1e293b',
        x: 1250,
        y: 1280,
        rotation: 0,
        opacity: 0.8,
      },
      {
        id: 'fsc_stamp',
        name: 'Stempel FSC',
        type: 'badge',
        badgeType: 'fsc',
        size: 90,
        color: '#1e293b',
        x: 800,
        y: 1280,
        rotation: 0,
        opacity: 0.8,
      },
    ],
  },
  {
    id: 'zen_matcha',
    title: 'Zen Ceremonial Matcha Pouch',
    modelId: 'standup_pouch',
    category: 'Coffee & Food',
    material: 'coated_matte',
    backgroundColor: '#1b2f21',
    accentColor: '#84cc16',
    lighting: 'warm_commercial',
    description: 'Pouch kemasan bubuk teh hijau Uji Kyoto dengan segel kedap udara & foil emas.',
    layers: [
      {
        id: 'matcha_kanji',
        name: 'Huruf Kanji',
        type: 'text',
        text: '宇治 抹茶',
        fontFamily: 'Inter',
        fontSize: 72,
        fontWeight: '700',
        color: '#e2e8f0',
        textAlign: 'center',
        letterSpacing: 10,
        lineHeight: 1,
        x: 520,
        y: 380,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'matcha_title',
        name: 'Nama Produk',
        type: 'text',
        text: 'CEREMONIAL GRADE MATCHA',
        fontFamily: 'Montserrat',
        fontSize: 26,
        fontWeight: '700',
        color: '#bef264',
        textAlign: 'center',
        letterSpacing: 4,
        lineHeight: 1.2,
        x: 520,
        y: 490,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'matcha_origin',
        name: 'Asal Daerah',
        type: 'text',
        text: 'FIRST HARVEST • UJI, KYOTO, JAPAN',
        fontFamily: 'Inter',
        fontSize: 16,
        fontWeight: '500',
        color: '#d1fae5',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1.2,
        x: 520,
        y: 560,
        rotation: 0,
        opacity: 0.9,
      },
      {
        id: 'matcha_seal',
        name: 'Sertifikasi Organik',
        type: 'badge',
        badgeType: 'organic',
        size: 90,
        color: '#bef264',
        x: 520,
        y: 720,
        rotation: 0,
        opacity: 1,
      },
      {
        id: 'matcha_weight',
        name: 'Berat',
        type: 'text',
        text: '100g / 3.5oz NET',
        fontFamily: 'Inter',
        fontSize: 18,
        fontWeight: '600',
        color: '#f8fafc',
        textAlign: 'center',
        letterSpacing: 2,
        lineHeight: 1,
        x: 520,
        y: 840,
        rotation: 0,
        opacity: 1,
      },
    ],
  },
];
